# Author's full name
author_name: René Coignard

# About section text
about_text: Political activist, human rights defender, and artist from Russia. Emigrated to Germany due to politically motivated persecution by the Russian government.  Previously known as Mikhail Podivilov.

# Prefix length in spaces for formatting paragraphs
prefix_length: 3

# Copyright text
copyright_text: contact@renecoignard.com
